# Sample kataManager configuration file
apiVersion: v1
data:
  config.yaml: |
    artifactsDir: /opt/nvidia-gpu-operator/artifacts/runtimeclasses
    runtimeClasses:
      - name: nvidia-gpu
        nodeSelector:
          nvidia.com/gpu.hopper: "true"
        artifacts:
          url: stg.nvcr.io/nvidia/cloud-native/kata-gpu-artifacts:ubuntu22.04-535
          pullSecret: <my-k8s-secret>
kind: ConfigMap
metadata:
  name: kata-manager-conf
  namespace: default
