# Sample kataManager configuration file
apiVersion: v1
data:
  config.yaml: |
    artifactsDir: /opt/nvidia-gpu-operator/artifacts/runtimeclasses
    runtimeClasses:
      - name: kata-qemu-nvidia-gpu
        artifacts:
          url: stg.nvcr.io/nvidia/cloud-native/kata-gpu-artifacts:ubuntu22.04-525
          pullSecret: <my-k8s-secret>
kind: ConfigMap
metadata:
  name: kata-manager-conf
  namespace: default
