apiVersion: apps/v1
kind: DaemonSet
metadata:
  generation: 1
  name: k8s-kata-manager
spec:
  selector:
    matchLabels:
      name: kata-manager
  template:
    metadata:
      labels:
        name: kata-manager
    spec:
      serviceAccountName: kata-manager-sa
      imagePullSecrets:
      - name: ghcrcred
      containers:
      - command: [bash, -c]
        args: ["sleep 5; exec k8s-kata-manager"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CONFIGURE_KATA
          value: "yes"
        - name: CONFIGURE_CC
          value: "no"
        image: ghcr.io/arangogutierrez/kkm:mark4.1
        imagePullPolicy: Always
        name: cc-runtime-install-pod
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/containerd/
          name: containerd-conf
        - mountPath: /run/containerd/containerd.sock
          name: containerd-socket
        - mountPath: /opt/nvidia-gpu-operator/artifacts/runtimeclasses/
          name: runtimeclass-artifacts
        - name: kata-manager-conf
          mountPath: "/etc/kubernetes/kata-manager/"
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kata-manager-conf
        configMap:
          name: kata-manager-conf
      - hostPath:
          path: /etc/containerd/
          type: ""
        name: containerd-conf
      - hostPath:
          path: /run/containerd/containerd.sock
          type: ""
        name: containerd-socket
      - hostPath:
          path: /opt/nvidia-gpu-operator/artifacts/runtimeclasses/
          type: DirectoryOrCreate
        name: runtimeclass-artifacts
