apiVersion: v1
kind: ServiceAccount
metadata:
  name: kata-manager-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kata-manager-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kata-manager-role-binding
subjects:
- kind: ServiceAccount
  name: kata-manager-sa
  namespace: default
roleRef:
  kind: Role
  name: kata-manager-role
  apiGroup: rbac.authorization.k8s.io